[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    -v
    --tb=short
    --strict-markers
    --color=yes
    -p no:warnings

markers =
    unitario: marca testes unitários
    bdd: marca testes BDD

bdd_features_base_dir = features/
